Fix npm publish
https://github.com/octokit/webhooks.js/pull/552 broke `npm publish` in
this repository by introduces `.ts`extensions to some imports (which
caused `npm publish` to fail with "error TS2691: An import path cannot
end with a '.ts' extension"). This fixes that by adding the ts-node.esm
configuration to tsconfig.json (which in turn required several
dependency bumps).